[pyprland]
plugins = [
    "fetch_client_menu",
    "layout_center",
    "lost_windows",
    "magnify",
    "scratchpads",
    "workspaces_follow_focus"
]

[scratchpads.skype]
animation = "fromRight"
class = "Skype"
command = "skypeforlinux"
size = "40% 80%"
margin = 50

[scratchpads.chat]
animation = "fromRight"
command = "/home/damaru/.config/hypr/scripts/perplexity"
class = "perplexity"
size = "40% 80%"
margin = 50

[_scratchpads.trl]
animation = "fromRight"
#command = "kitty --class ollama ollama run phi3:14b"
command = "/home/damaru/.config/hypr/scripts/trl"
class = "trl"
size = "40% 80%"
margin = 50

[scratchpads.thunar]
animation = "fromRight"
#command = "kitty --class ollama ollama run phi3:14b"
command = "thunar"
class = "thunar"
size = "40% 80%"
margin = 50
unfocus = "hide"

[_scratchpads.calc]
animation = "fromRight"
command = "gnome-calculator"
class = "org.gnome.Calculator"
size = "20% 50%"
margin = 50
unfocus = "hide"


[_scratchpads.twitter]
animation = "fromRight"
#command = "kitty --class ollama ollama run phi3:14b"
command = "/home/damaru/.config/hypr/scripts/twitter"
class = "twitter"
size = "40% 80%"
margin = 50
unfocus = "hide"
