#!/bin/sh

function monitor() {
    local monitor=`hyprctl -j monitors | jq -r '.[0].name'`
    #echo "Capturing: ${monitor}"
    hyprctl -j monitors | jq '.[0]' | jq -r '"\(.x),\(.y) \(.width/.scale|round)x\(.height/.scale|round)"'
}

function area() {
  slurp
}

window() {
  w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
    w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
    echo "$w_pos $w_size"
}

OUTPUT=/tmp/shot-$(date +%s).png

function save_geometry() {
    local geometry="${1}"
    echo "Geometry: ${geometry} => Output: ${OUTPUT}"
    grim -g "${geometry}" "$OUTPUT"
    wl-copy --type image/png < "$OUTPUT"
    #swappy -f "$OUTPUT"
    satty --filename "$OUTPUT"
    rm -f "$OUTPUT" &
}

save_geometry "$($1)" 

