#!/usr/bin/bash

MONITORS=$(hyprctl monitors)
CLIENTS=$(hyprctl clients)
CURRENT_MONITOR=$(echo "$MONITORS" | grep -e Monitor -e focused:  | grep focused:\ yes -B1 | head -1| awk '{print $2}')
CURRENT_WOKSPACE=$(echo "$MONITORS" | grep -e Monitor -e active\ workspace:  | grep $CURRENT_MONITOR -A1 | tail -1| awk '{print $3}')
XPOS=55%
YPOS=10%
WIDTH=40%
HEIGHT=80%

prop() {
WINDOW=$(echo "$CLIENTS" | grep -e Window -e class | grep class:\ $1 -B1 | head -1 | awk '{print $2}')
if [ "$WINDOW" == "" ]; then
  echo ""
  return -1
fi
echo $(echo "$CLIENTS" | grep -e $WINDOW -e $2 | grep $WINDOW -A1 | tail -1 | awk -F$2: '{print $2 $3}')
}

pull(){
CLASS=$1
WINDOW=address:0x$(echo "$CLIENTS" | grep -e Window -e class | grep class:\ $CLASS -B1 | head -1 | awk '{print $2}')
#echo $CLASS $WINDOW $CURRENT_MONITOR
hyprctl --batch "<<<END
keyword windowrule unset,^(${CLASS})\$;
dispatch resizewindowpixel exact $WIDTH $HEIGHT,$WINDOW;
dispatch moveworkspacetomonitor special:scratchpad $CURRENT_MONITOR;
dispatch movetoworkspacesilent $CURRENT_WOKSPACE,$WINDOW;
dispatch alterzorder top,$WINDOW;
dispatch movewindowpixel exact $XPOS $YPOS,$WINDOW;
dispatch focuswindow $WINDOW;
dispatch pin $WINDOW;
END"
}



push() {
CLASS=$1
WINDOW=address:0x$(echo "$CLIENTS" | grep -e Window -e class | grep class:\ $CLASS -B1 | head -1 | awk '{print $2}')
echo $CLASS $WINDOW
hyprctl --batch "dispatch movewindowpixel 200% $YPOS,$WINDOW; dispatch pin $WINDOW; dispatch movetoworkspacesilent special:scratchpad,$WINDOW;"
}

waitwin() {
  while [[ True ]]; do
    CLIENTS=$(hyprctl clients)
    echo "$CLIENTS" | grep class:\ $1 && return 0;
    echo wait $1
    sleep 1
  done
}

create() {
 hyprctl --batch "keyword windowrule float,^($1)\$ ; keyword windowrule workspace special:scratchpad silent,^($1)\$ ; keyword windowrule move 1408 200%,^($1)\$ ; keyword windowrule size 1024 1152,^($1)\$"
if [ -f "~/.config/hypr/scripts/$1" ]; then
  echo "script found ~/.config/hypr/scripts/$1"
  ~/.config/hypr/scripts/$1
else
  $1 & 
fi
waitwin $1; 
}

toggle() {
  ((prop $1 pid  && ((prop $1 workspace | grep scratchpad && pull $1) || push $1)) || (create $1 ; pull $1))
}

status(){
  echo "Monitor: $CURRENT_MONITOR"
  echo "workspace: $CURRENT_WOKSPACE"
}

com.damaru.ollama(){
  ghostty --class=com.damaru.ollama -e ollama run llama2:7b
}

Jan(){
  /opt/Jan/jan --ozone-platform=wayland $@
}

CMD=$1
shift
$CMD "$@"
