#!/bin/bash

export PATH=$PATH:/home/damaru/bin

#export LD_LIBRARY_PATH=/usr/local/lib
#unset STY
cprj()
{

	if [ -z "$1" ]; then
		PR=`cat ~/.project`; 
	else
		PR=$1
	fi
	cd $PR
	if [ -f env.sh ]; then
		. env.sh
	fi
}

cprj

#hyprctl clients|grep -e Window -e  class | grep -B1 tmux  | tee -a /tmp/shell.log
ID=$(hyprctl clients | grep -e Window -e  class | grep -B1 com.mitchellh.ghostty.tmux | head -1 | /home/damaru/bin/nth 1)
MON=$(hyprctl monitors | grep active\ workspace | /home/damaru/bin/nth 2)
#message $MON,address:0x$ID
#$echo "ID:$ID" | tee -a /tmp/shell.log
#echo "MON:$MON" | tee -a /tmp/shell.log
WIN=address:0x$ID
if [ -z $ID ]; then
  #echo "NO WINDOW:$ID" | tee -a /tmp/shell.log
  #message 'NO WINDOW:$ID'
  exec ghostty --class=com.mitchellh.ghostty.tmux -e tmux new-session -AD -s tmux
else
  #message $WIN
  #echo "WINDOW:$ID"  | tee -a /tmp/shell.log
  #hyprctl dispatch movetoworkspace $MON,$WIN
  hyprctl dispatch focuswindow $WIN && exit
  exec ghostty --class=com.mitchellh.ghostty.tmux -e tmux new-session -AD -s tmux
fi

exit

